version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gql_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: graphql_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d graphql_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: gql_backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/graphql_db?schema=public"
      PORT: 4000
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run dev
      "

volumes:
  pgdata:
